### PR TITLE
Support multiple caches

### PR DESCRIPTION
**Pull request by kddnewton**
Hi there! I like this thing, but it doesn't support Redis. I've refactored it to run through Fastentry.cache instead of Rails.cache so that it can decorate the cache with support for pulling out keys in different ways.

### CODE REVIEW

**Comment by alvesjtiago** [comment]
Hi @kddeisz, this is fantastic! I was planning on refactoring later after validating that this was a real need of the community but your PR completely corroborates this. Going to test and merge.

Thank you for improving FastEntry and if you have the time it would be great to get in touch and discuss what made you take an interest on the engine and what you'd like to see in the future.

Thanks once again.

**Comment by kddnewton** [comment]
No worries! I'm very interested in this kind of dashboard for caching. My current app is REALLY heavy on the cache, and there have been a couple of times where I've needed to SSH into production boxes literally just to `touch` records to bust their caches. It'd be great to avoid this entirely.

For that matter, here are two things (no pressure!) that would be super useful:

- I've had to monkey patch it right now because `.assets` is only available if you're running in non api-only mode. Hopefully I can get a PR up for that at some point.
- Deleting multiple caches at the same time would be huge. That's usually the case for me (some org updates and all the users in the org need to be busted kind of thing).

Either way great work! I'll be watching this repo!

**Comment by alvesjtiago** [comment]
@kddeisz those are great ideas and definitely worth implementing! I'll start with the second one since I've received that feedback from other people who have been testing FastEntry. Regarding the first one you're absolutely right: there needs to be a way to not rely on the `assets` part for the engine to work. I'll setup a test project in api-only mode to debug this.

Thanks again for the amazing feedback.

**Comment by alvesjtiago** [comment]
@kddeisz version 0.1.10 now supports multiple cache keys invalidation.

**Comment by kddnewton** [comment]
Nice work!!

**Comment by alvesjtiago** [comment]
Thanks @kddeisz!

Regarding the other issue, on api-only mode there's a commented line on `application.rb`:

```# require "sprockets/railtie"```

Uncommenting that line should make it work without having to monkey patch anything else. Would it be possible for you to try that? Thank you 😊

**Comment by kddnewton** [comment]
Yup that fixed it!

**Pull request merged**
